### ISSUE TITLE
logos for Arena, ChessGUI, WinBoard Interface etc. (130x65, bitmap)

### ISSUE THREAD

**Issue by yellow-panther** [thorsilver/SpaceDog#8]
Hello thorsilver,
can you make a Windows 32 or 64 bit binary of Space Dog please? Unfortunately I am not a programmer.

cf. attached files here: 
[Space Dog logos.zip](https://github.com/thorsilver/SpaceDog/files/2875658/Space.Dog.logos.zip)

Regards,

**Comment by thorsilver** [comment]
Hi!  Wow thanks for the logos, those are great :)

I'll whip up a new Windows binary later tonight for sure.  It will need cygwin.dll to run, either in the SpaceDog folder itself or just having Cygwin installed on your system should work.  Also apologies in advance for inevitable bugs and deficiencies!  Very much a work-in-progress and a learning experience for me.

**Comment by thorsilver** [comment]
Made a new bugfix release (0.97.1) which includes Windows and Linux builds.  Please see the release for details.  These builds are rush jobs so may contain new and exciting bugs, but my quick tests seem fine so far.  Before I get to v1.0 I'll squash more bugs and SpaceDog will be a much leaner chess sparring partner by then :)

**Comment by thorsilver** [comment]
Another update: new release 0.97.3 has a fixed Windows build that no longer requires Cygwin.  It's also slightly faster in my tests (between 3.5-4Mnps on an i5-4790K CPU, as compared to 2.5-3.5Mnps on the Cygwin build).
